# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 560ad606e12bd8d43c34e03fdb0c83695f0a9b08e946690d697cd06ab12bb93e5fba6b30fae50c33eff52b209d3817585ceab7cae052db3a5a1639e7d81ba8e1

test:
  secret_key_base: fd55f3dc78cfbaf9d1aa34417b2576c2e3862bbfdc331fafe8f1282f3461072ee93cfb7ed851013bc53bec767efcedb0ab334827abe24007558cea7a72aaf7c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
